name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive    
    - name: Install cURL Headers
      run: sudo apt-get install libcurl4-openssl-dev
    - name: make
      run: make    

